### ISSUE TITLE
Cricleci Bot generates broken links

### ISSUE THREAD

**Issue by n-srg** [n0th1ng-else/minimal-store#5]
github comment does not make any sense at the moment

**Comment by n-srg** [comment]
this might be the case:

https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs

https://circleci.com/blog/persisting-data-in-workflows-when-to-use-caching-artifacts-and-workspaces/

**Comment by n0th1ng-else** [comment]
https://github.com/n0th1ng-else/minimal-store/pull/6
